[package]
name = "mcgen"
version = "1.0.0"
authors = ["Nico Madysa <nico.madysa@tu-dresden.de>"]

[dependencies]
rand = "0.3.15"
gnuplot = "0.0.22"
csv = "1.0.0-beta.3"
serde = "^1.0.10"
dimensioned = "0.6.0"
